"$schema" = "https://starship.rs/config-schema.json"

command_timeout = 1500

format = """
[î‚¶](fg:color_bg1)\
$os\
$username\
$hostname\
[î‚´ ](fg:color_bg1 bg:color_bg2)\
$directory\
[î‚´ ](fg:color_bg2 bg:color_bg3)\
$git_branch\
$git_status\
[î‚´ ](fg:color_bg3 bg:color_bg4)\
$c\
$dotnet\
$java\
$kotlin\
$nodejs\
$python\
[î‚´ ](fg:color_bg4 bg:color_bg5)\
$cmd_duration\
[î‚´ ](fg:color_bg5)\
\n$character\
"""

palette = "ccswe_dark"

[palettes.ccswe_dark]
color_bg1 = "#336699"
color_bg2 = "#2f5783"
color_bg3 = "#294262"
color_bg4 = "#232f44"
color_bg5 = "#1d2230"

color_blue = "#769ff0"
color_gray = "#999999"
color_red = "#eb4d28"
color_white = "#f2f2f2"

[character]
error_symbol = "[â¯](bold color_red)"
success_symbol = "[â¯](bold color_blue)"

[cmd_duration]
format = "[$duration](bg:color_bg5 fg:color_gray)"
min_time = 500

[directory]
style = "bg:color_bg2 fg:color_white"
format = "[$path]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[git_branch]
symbol = "ï˜"
style = "bg:color_bg3 fg:color_blue"
format = "[$symbol $branch]($style)"

[git_status]
ahead = "â‡¡${count}"
behind = "â‡£${count}"
deleted = "ï’"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
format = '[( $all_status$ahead_behind)]($style)'
style = "bold bg:color_bg3 fg:color_red"

[hostname]
format = "[@$hostname]($style)"
ssh_only = true
ssh_symbol = "î¬ "
style = "bg:color_bg1 fg:color_white"

[os]
format = "[$symbol]($style)"
style = "bg:color_bg1 fg:color_white"
disabled = false

[username]
disabled = false
format = "[$user]($style)"
show_always = false
style_root = "bg:color_bg1 fg:color_red"
style_user = "bg:color_bg1 fg:color_white"

# Code symbols
[c]
format = '[$symbol]($style)'
style = "bg:color_bg4 fg:#6295CB"
symbol = "î˜ "

[dotnet]
format = '[$symbol]($style)'
style = "bg:color_bg4 fg:#1180C3"
symbol = "î¿ "

[java]
format = '[$symbol]($style)'
style = "bg:color_bg4 fg:#F7901E"
symbol = "î‰– "

[kotlin]
format = '[$symbol]($style)'
style = "bg:color_bg4 fg:#C017E4"
symbol = "î˜´ "

[nodejs]
style = "bg:color_bg4 fg:#5FA04E"
format = '[$symbol($version)]($style)'
symbol = "îœ˜ "

[python]
symbol = "ğŸ "
style = "bg:color_bg4 fg:#3776AB"
format = '[$symbol($version) (\($virtualenv\))]($style)'



# OS Symbols
[os.symbols]
# Alpaquita = "îª¢ "
# Alpine = "ïŒ€ "
# AlmaLinux = "ïŒ "
# Amazon = "ï‰° "
# Android = "ï…» "
Arch = "ïŒƒ "
# Artix = "ïŒŸ "
# CentOS = "ïŒ„ "
# Debian = "ïŒ† "
# DragonFly = "îŠ "
# Emscripten = "ïˆ… "
# EndeavourOS = "ï†— "
# Fedora = "ïŒŠ "
# FreeBSD = "ïŒŒ "
# Garuda = "ó°›“ "
# Gentoo = "ïŒ "
# HardenedBSD = "ó°Œ "
# Illumos = "ó°ˆ¸ "
# Kali = "ïŒ§ "
# Linux = "ïŒš "
# Mabox = "î¬© "
# Macos = "ïŒ‚ "
# Manjaro = "ïŒ’ "
# Mariner = "ï‡ "
# MidnightBSD = "ï†† "
# Mint = "ïŒ "
# NetBSD = "ï€¤ "
# NixOS = "ïŒ“ "
# OpenBSD = "ó°ˆº "
# openSUSE = "ïŒ” "
# OracleLinux = "ó°Œ· "
# Pop = "ïŒª "
# Raspbian = "ïŒ• "
# Redhat = "ïŒ– "
# RedHatEnterprise = "ïŒ– "
# RockyLinux = "ïŒ« "
# Redox = "ó°€˜ "
# Solus = "ó° ³ "
# SUSE = "ïŒ” "
# Ubuntu = "ïŒ› "
# Unknown = "ïˆ­ "
# Void = "ïŒ® "
# Windows = "ó°² "
